update rich text editor
ZEnMo/Holon-webapp pull request #155
Opened 2022-11-09 10:09 UTC by pascalalferink

2022-11-09 12:14 UTC, MariaBee3 commented
Looks really nice. I had one small suggestion, but I leave it up to you if it is overkill or not.

2022-11-15 11:49 UTC, MariaBee3 requested changes

2022-11-15 12:13 UTC, pascalalferink commented on frontend/components/RawHtml/RawHtml.module.css
>  }
@MariaBee3  I have changed the code,  could you take another look at at?
![image](https://user-images.githubusercontent.com/13336728/201917224-5a9e433d-0968-4064-a12e-45c474370344.png)

2022-11-15 12:23 UTC, MariaBee3 approved these changes

2022-11-15 12:26 UTC, merged