110 users can get more information on terms in the wiki
ZEnMo/Holon-webapp pull request #170
Opened 2022-11-15 10:59 UTC by pascalalferink

2022-11-15 14:24 UTC, antw reviewed
The code looks good to me, but I haven't been able to test it because I can't figure out how to create text that links to a StaticTermPage. 😕

I have a Static page and a StaticTermPage, and within the Static have tried writing text (that gets rendered by RawHtml) with the same name as the StaticTermPage. I tried both the value for the "Introduction" and the page title, and also tried linking to it directly but don't get any underlined text or a modal. Am I doing something wrong?

2022-11-17 08:14 UTC, mattijsstam commented
> The code looks good to me, but I haven't been able to test it because I can't figure out how to create text that links to a StaticTermPage. 😕
> 
> I have a Static page and a StaticTermPage, and within the Static have tried writing text (that gets rendered by RawHtml) with the same name as the StaticTermPage. I tried both the value for the "Introduction" and the page title, and also tried linking to it directly but don't get any underlined text or a modal. Am I doing something wrong?

@antw you have to highlight text in the rich text editor and then you can replace the highlighted text with a term. I agree that the default interface is not intuitive

2022-11-17 09:49 UTC, antw requested changes
I was able to test the modal (thanks @mattijsstam!) and found two small issues. Other than those, this feature worked perfectly.

2022-11-17 09:49 UTC, antw commented on frontend/components/RawHtml/RawHtml.tsx
> +                      onClick={closeModal}
A button with no text content needs an [accessible label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) for screen readers.

```suggestion
                      onClick={closeModal}
                      aria-label="Sluiten"
```

2022-11-17 09:49 UTC, antw commented on frontend/components/RawHtml/RawHtml.tsx
> +          <Dialog as="div" className="relative z-10" onClose={closeModal}>
This z-index is too low. The header has a value of 50, and if the viewport is small this causes the modal to be overlapped by the header:

<img width="518" alt="Screenshot 2022-11-17 at 09 39 45" src="https://user-images.githubusercontent.com/4383/202412620-4f2f501c-98a9-467c-95c4-0cada1c86833.png">

```suggestion
          <Dialog as="div" className="relative z-50" onClose={closeModal}>
```

2022-11-17 10:31 UTC, antw approved these changes

2022-11-17 10:55 UTC, pascalalferink commented on frontend/components/RawHtml/RawHtml.tsx
> +  }
Hi @antw , I agree with you that 3 lines of setState is unnecessary . I refactored the code, while not implementing the reducer. Hence the three properties are always changed together, I merged the three states into one object (Modal) with three properties.

Is this OK with you?

2022-11-17 11:21 UTC, antw commented on frontend/components/RawHtml/RawHtml.tsx
> +  }
Thanks, I think that's much better; and simpler than using the reducer as well. :+1:

2022-11-17 11:21 UTC, antw submitted a review, later dismissed

2022-11-18 11:41 UTC, broekhuisg approved these changes
Getest en het werkt. Echt super tof gedaan!

2022-11-18 11:46 UTC, merged