Draft!: 174 content managers can add overview pages to quickly show a list of cards
ZEnMo/Holon-webapp pull request #299
Opened 2023-01-18 09:07 UTC by broekhuisg

Deze story is nog niet klaar om te mergen, maar ik maak wel even een PR aan, omdat het makkelijker is om code te vergelijken zo.

De status is:
- backend is voornamelijk aangepakt waarbij:
- - casuspage type is aangemaakt. Als child (linked) kan je een storyline / challenge mode / sandbox (new) aanmaken. Het is nog niet mogelijk om er slechts 1 aan te maken
- - een casus pagina heeft een filter, die je kan vullen via de snippets (gemeente, nationaal ...)
- - een nieuwe overview pagina type aangemaakt, waarbij je kan selecteren welke overview je wilt hebben (storyline/casus/bestpractice/sandbox/challengemode). Deze overviews laten voor nu alle pagina's zien van de bijbehorende type die live staan. Het idee is om storylineoverviewpage uit te faseren.
- - een nieuw type bestpractice, die je kan koppelen aan een casus. 0 of meer.
- - frontend is nog niet echt wat mee gedaan

Ben ik zo op de goede weg? Ik hoor het graag.

2023-02-01 15:46 UTC, thesethtruth commented
Should also close #279

2023-02-02 12:41 UTC, mattijsstam requested changes
Nog een paar puntjes:
- zie commentaar bij de bestanden voor het neerzetten van meer generieke streamfield afhandeling in de frontend
- Je kunt nu een body toevoegen aan de casusoverviewpagina maar hier gebeurt verder niets mee, bij de best practices werkt dit wel. Mijn voorstel zou zijn om dit op dezelfde manier op te lossen. Ik zat nog te denken dat je ook een soort placeholder block kunt maken voor de cards zodat de content managers zelf de pagina indeling kunnen maken en vrij eenvoudig tekst boven en onder de cards kunnen plaatsen.

2023-02-02 12:41 UTC, mattijsstam commented on frontend/containers/BestPracticeOverviewPage/BestPracticeOverviewPage.tsx
> +        }
Het viel me op dat dit element een aantal keer terug komt, misschien mooier om hier 1 generiek component van te maken en op elke pagina met een streamfield toe te passen

2023-02-02 12:41 UTC, mattijsstam commented on frontend/containers/BestPracticePage/BestPracticePage.tsx
> +          default:
zie opmerking op de bestpractice overview page

2023-02-02 12:41 UTC, mattijsstam commented on frontend/containers/CasusPage/CasusPage.tsx
> +        }
zie vorige opmerkingen

2023-02-02 12:41 UTC, mattijsstam commented on frontend/containers/InteractiveOverviewPage/InteractiveOverviewPage.tsx
> +        }
Ook dit kan misschien samengevoegd worden of vervangen worden door een generiek herocomponent

2023-02-02 14:38 UTC, mattijsstam approved these changes

2023-02-02 14:40 UTC, mattijsstam submitted a review, later dismissed

2023-02-03 07:39 UTC, pascalalferink approved these changes

2023-02-03 07:39 UTC, merged