314 menu items in header disappear when page is not made in wagtail
ZEnMo/Holon-webapp pull request #328
Opened 2023-02-09 07:47 UTC by pascalalferink

2023-02-09 08:53 UTC, mattijsstam requested changes
Naast dat ik de oplossing niet echt mooi vind gaat het gebruik van getStaticProps problemen opleveren als het menu verandert nadat de website gebouwd en gedeployt is. Een oplossing zou zijn om getServerSideProps te gebruiken maar ik zou liever het volgende zien:

1. In het [...path].tsx bestand een try catch block toevoegen aan de getServerSideProps functie waarbij wordt gecheckt of de aangeroepen url voorkomt in een lijst met niet wagtail urls + componentnaam
2. Hier een api request aanroepen die alleen het menu teruggeeft zoals je nu in de getstaticprops hebt gedaan met dus de componentnaam uit de lijst
3. Daarna  kan je de default LazyContainers gebruiken om de "niet wagtail pagina's" aan toe te voegen, hierbij moeten de "niet wagtail pagina's" wel op dezelfde manier zijn opgebouwd als de andere containers dus met de basePageWrap() functie. Dit kun je garanderen door het npm run new:container <PageName> command te gebruiken voor alle pagina's. 

Op deze manier heb je 1 getserversideprops functie die alles regelt en kun je eenvoudig nieuwe pagina's toevoegen, het enige wat je per pagina moet doen is dit aan de lijst toevoegen.

Als de lijst als volgt is opgebouwd kun je eenvoudig een url naar een componentName vertalen:

[
{"/inloggen/": "LoginPage"}
]

Misschien goed om het hier vandaag nog even over te hebben als het niet helemaal duidelijk is.

2023-02-09 08:53 UTC, mattijsstam commented on frontend/pages/inloggen.tsx
> +export default function TilesDemo({
```suggestion
export default function LoginPage({
```

2023-02-10 09:54 UTC, broekhuisg commented
@mattijsstam bump. Heb het volledig omgeschreven! Veel betere oplossing zo. Thanks!

2023-02-13 08:06 UTC, broekhuisg approved these changes

2023-02-13 08:07 UTC, broekhuisg commented on frontend/pages/inloggen.tsx
> +export default function TilesDemo({
@mattijsstam Kan je dit nog even goedkeuren? Dit blokkeert de merge

2023-02-13 08:11 UTC, mattijsstam approved these changes

2023-02-13 08:14 UTC, merged