333 holarchie de gebruiker kan de kpis in een overzicht zien per niveau nationaal lokaal en tussenniveau in rechter deel dashboard
ZEnMo/Holon-webapp pull request #362
Opened 2023-02-20 07:26 UTC by pascalalferink

2023-02-23 13:56 UTC, mattijsstam requested changes

2023-02-23 13:56 UTC, mattijsstam commented on frontend/components/KPIDashboard/HolarchyKPIDashboard.tsx
> +              unit="%"></KPIItem>
Dit dashboard is nagenoeg hetzelfde als het dashboard op de storyline zelf. Het op deze manier op meerdere plekken definieren is foutgevoelig en volgens mij is het beter om hier 1 component van te maken waar je de data aan meegeeft ipv de 4 KPIIems hier te definieren.

2023-02-23 13:56 UTC, mattijsstam commented on frontend/components/KPIDashboard/KPIDashboard.tsx
>            value={valueCheck(data[level].selfSufficiency)}
Zie commentaar bij HolarchyKPIDashboard.tsx

2023-02-23 15:41 UTC, MariaBee3 commented on frontend/components/KPIDashboard/KPIDashboard.tsx
>            value={valueCheck(data[level].selfSufficiency)}
component KPIItems aangemaakt waardoor dubbele code wordt weggehaald.

2023-02-23 15:46 UTC, MariaBee3 approved these changes

2023-02-24 08:56 UTC, mattijsstam approved these changes

2023-02-24 08:57 UTC, merged