336 kostenbaten de grafiek toont per actor categorie de lasten en baten op een verticale lijn boven en onder de nullijn met barplots
ZEnMo/Holon-webapp pull request #370
Opened 2023-02-22 10:21 UTC by broekhuisg

@pascalalferink Zou jij deze functioneel willen testen? Ik heb na de changes die jij hebt gemaakt, ook nog changes gemaakt. Daarna kan iemand anders nog naar de code kijken.

2023-02-23 13:35 UTC, MariaBee3 commented
Alles lijkt goed te werken. Pascal kijkt nog even naar de grootte van de tabel. Voor mergen nog even wachten op reactie @mattijsstam op api url met of zonder /.

2023-02-23 15:06 UTC, pascalalferink commented
Grafiek past op de pagina: 
![image](https://user-images.githubusercontent.com/13336728/220945799-4e1cd01b-f16e-48bb-9863-30bbe20bb083.png)

2023-02-23 15:07 UTC, pascalalferink submitted a review, later dismissed

2023-02-24 08:01 UTC, mattijsstam requested changes

2023-02-24 09:18 UTC, MariaBee3 commented on frontend/components/Charts/KostenBatenChart.tsx
> +      .catch(err => console.log(err));
Alle API calls rondom charts zijn nu toegevoegd aan het holon.ts bestand.

2023-02-24 09:29 UTC, MariaBee3 commented on frontend/components/Charts/KostenBatenChart.tsx
> +const API_URL = process.env.NEXT_PUBLIC_BASE_URL || "";
Alle API calls rondom charts zijn nu toegevoegd aan het holon.ts bestand.

2023-02-27 08:49 UTC, merged