420 cloudclient
ZEnMo/Holon-webapp pull request #428
Opened 2023-03-10 12:45 UTC by thesethtruth

To do:
- [ ] Finish sketchview
- [ ] Implement cloudclient mini
- [ ] Read db config
- [ ] Handback results (raw)
- [ ] Parse results based on db config

2023-03-14 15:05 UTC, mattijsstam requested changes

2023-03-14 15:05 UTC, mattijsstam commented on src/holon/views/holon.py
> +            status=status.HTTP_418_IM_A_TEAPOT,
beter http 410 Gone gebruiken

2023-03-14 15:51 UTC, thesethtruth commented on src/holon/views/holon.py
> +            status=status.HTTP_418_IM_A_TEAPOT,
Maar die andere is zo leuk!

2023-03-14 15:51 UTC, thesethtruth commented on src/holon/views/holon.py
> +                # scenario.delete()
Ah, goed punt. Kijk ik naar.

2023-03-15 08:39 UTC, mattijsstam approved these changes

2023-03-15 08:39 UTC, mattijsstam commented on src/holon/views/holon.py
> +                    cc.outputs,
ik merk dat het bij reviews soms helpt om te doen alsof je dom bent dus even een check voor de zekerheid, de outputs die hier worden teruggestuurd zijn nog niet de definitieve outputs waarmee de frontend kan werken?

2023-03-15 09:10 UTC, merged

2023-03-15 09:10 UTC, thesethtruth commented on src/holon/views/holon.py
> +                    cc.outputs,
Nee, klopt! Dat wordt nog gedaan.