569 2nd order relation filter
ZEnMo/Holon-webapp pull request #596
Opened 2023-04-11 08:29 UTC by SCHS13

Voegt 2e order relatie veld

- [ ] In het CMS moeten de dropdowns van SecondOrderRelationField goed gevuld worden

#### Uitleg attributen:
- Relation field: relatieveld van gekozen modeltype bij scenariorule **(hetzelfde)**
- Relation field subtype: subtype van gekozen relatieveld **(hetzelfde)**
- Second order relation field: relatieveld van modeltype gekozen bij Relation field subtype of relation field **(nieuw)**
- Second order relation field subtype: subtype van gekozen model bij second order relation field **(nieuw)**
- Model attribute: attribute voor vergelijking van Second order relation field's model of Second order relation field subtype **(anders)**

2023-04-17 08:54 UTC, SCHS13 commented
@mattijsstam Bij het opnieuw openen van een interactief element met een second order relation filter worden niet alle inputs als dropdown geladen. Is dit iets wat opgelost kan worden of is het technisch beperkt?
![image](https://user-images.githubusercontent.com/124364901/232431131-bfba2e26-000e-44d2-9c92-d4a3706dc5ed.png)

2023-04-17 09:42 UTC, mattijsstam commented
@SCHS13 dit zal ik toevoegen, is niet heel veel moeite

2023-04-19 10:44 UTC, TAVMWB requested changes

2023-04-19 10:44 UTC, TAVMWB commented on src/holon/models/filter.py
>          verbose_name = "RelationAttributeFilter"
should be updated

2023-04-19 10:44 UTC, TAVMWB commented on src/holon/models/filter.py
Should there also be a `SecondOrderRelationExists` filter? Just like the first-order versions. 
I do not know whether there is demand for an attribute second-order relation filter or just whether it exists or not.

2023-04-19 11:45 UTC, SCHS13 commented on src/holon/models/filter.py
>          verbose_name = "RelationAttributeFilter"
I updated to code

2023-04-19 11:45 UTC, SCHS13 commented on src/holon/models/filter.py
That'd be a new feature so for now I'd say no

2023-04-19 11:51 UTC, SCHS13 commented
> Wanneer je een second order relation type aan wilt passen in een filter moet je altijd de complete boom doorlopen. Dus Relation field -> Relation field subtype -> Second order relation field -> Second order relation field subtype en dan klopt alle data.

Ik heb het aan de wiki toegevoegd. Dit lijkt me een goede afweging

2023-04-19 19:19 UTC, merged